<?php
/* Starting data for a fresh install. On first load it is copied to data/store.php,
   and from then on everything is edited in admin.php — not here. */
if(!defined('FK_ROOT')){ http_response_code(404); exit; }

return [
  'settings' => [
    'brand'         => 'FUDAKURA',
    'kanji'         => '札蔵',
    'tagline'       => 'Wholesale Japanese Pokémon TCG',
    'legal_name'    => 'Fudakura',
    'address'       => 'Japan',
    'email'         => 'support@fudakura.store',
    'phone'         => '',
    'order_email'   => 'support@fudakura.store',
    'domain'        => 'https://fudakura.store',
    'reply_hours'   => 12,
    'hold_hours'    => 48,
    'min_order_usd' => 100,
    'strip_text'    => 'Sealed product, sourced in Japan · Quantity breaks published on every listing',
    'strip_link_text' => 'Aura Seeker preorders open →',
    'strip_link_url'  => 'index.php?p=product&id=aura-seeker-booster-box',
    'hero_title'    => 'Wholesale Japanese Pokémon cards, shipped worldwide from Japan.',
    'hero_lede'     => 'Sealed booster boxes, Elite Trainer Boxes, premium sets and singles, bought through Japanese distribution and priced by the case. Every quantity break is published — price a full order before you talk to anyone.',
    'footer_blurb'  => 'Wholesale Japanese Pokémon TCG, shipped worldwide from Japan to retailers, resellers and card shops. Pricing published on every product — order direct, no account needed.',
    'shipping_reviewed' => false,
  ],

  'currencies' => [
    'USD' => ['rate'=>1,    'sym'=>'$',   'dec'=>2],
    'EUR' => ['rate'=>0.87635, 'sym'=>'€', 'dec'=>2],
    'JPY' => ['rate'=>156,  'sym'=>'¥',   'dec'=>0],
    'GBP' => ['rate'=>0.79, 'sym'=>'£',   'dec'=>2],
    'CAD' => ['rate'=>1.37, 'sym'=>'CA$', 'dec'=>2],
    'AUD' => ['rate'=>1.52, 'sym'=>'A$',  'dec'=>2],
  ],

  'categories' => [
    'boxes'       => ['label'=>'Booster Boxes',         'blurb'=>'Sealed Japanese booster boxes, shipped by the case.'],
    'etb'         => ['label'=>'Elite Trainer Boxes',   'blurb'=>'ETBs and starter sets with sleeves, dice and promos.'],
    'premium'     => ['label'=>'Premium & Special Sets','blurb'=>'Premium decks, collection boxes and limited commemoratives.'],
    'singles'     => ['label'=>'Single Cards',          'blurb'=>'Graded and raw singles, including SAR, AR and promos.'],
    'accessories' => ['label'=>'Accessories',           'blurb'=>'Sleeves, deck boxes, playmats and storage.'],
  ],

  /* status: in | new | low | preorder | soldout.  cond: Sealed | Graded | Near Mint | Lightly Played.
     ladder: [min_qty, unit_price_usd] ascending.  weight: kg per unit (used for shipping) */
  'products' => [
    ['id'=>'storm-emeralda-elite-trainer-box', 'sku'=>'FK-ETB-SE-01',
     'name'=>'Storm Emeralda Elite Trainer Box', 'set'=>'Storm Emeralda', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,45.00],[6,38.00],[18,36.00],[36,34.00]],
     'desc'=>'Japanese Elite Trainer Box for the Storm Emeralda expansion. Sealed factory case, includes card sleeves, damage counters, dice, energy cards and the set promo. Sold in multiples of six.'],
    ['id'=>'30th-celebration-m6a-booster-box', 'sku'=>'FK-BB-M6A-01',
     'name'=>'30th Celebration (M6A) Booster Box', 'set'=>'30th Celebration', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,327.00],[6,279.00],[12,267.00],[24,255.00]],
     'desc'=>'Anniversary booster box from the 30th Celebration series. High pull-rate set with reprinted classic illustrations. Sealed Japanese domestic release.'],
    ['id'=>'mega-rayquaza-ex-mur', 'sku'=>'FK-SGL-MRAY-MUR',
     'name'=>'Mega Rayquaza ex — Master Ultra Rare (Japanese)', 'set'=>'Storm Emeralda', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,1207.30],[3,1150.00],[6,1092.90]],
     'desc'=>'Japanese Master Ultra Rare Mega Rayquaza ex. Pack-fresh, sleeved and toploaded on dispatch. Condition graded NM unless otherwise noted on the invoice.'],
    ['id'=>'mega-gengar-ex-sir', 'sku'=>'FK-SGL-MGEN-SIR',
     'name'=>'Mega Gengar ex — Special Illustration Rare', 'set'=>'Mega Dream ex', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,1033.50],[3,985.00],[6,935.60]],
     'desc'=>'Japanese Special Illustration Rare Mega Gengar ex. Pack-fresh, sleeved and toploaded on dispatch. Condition graded NM unless otherwise noted.'],
    ['id'=>'30th-celebration-elite-trainer-box', 'sku'=>'FK-ETB-30C-01',
     'name'=>'30th Celebration Elite Trainer Box', 'set'=>'30th Celebration', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>4, 'step'=>4, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,48.99],[4,44.00],[24,33.20]],
     'desc'=>'Elite Trainer Box from the 30th Celebration anniversary series, factory sealed. Sold in fours, with the lowest per-unit price from 24 boxes.'],
    ['id'=>'storm-emeralda-m6-booster-box', 'sku'=>'FK-BB-M6-01',
     'name'=>'Storm Emeralda (M6) Booster Box', 'set'=>'Storm Emeralda', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,218.00],[6,185.00],[24,170.00]],
     'desc'=>'Sealed Japanese booster box from Storm Emeralda (M6), the Mega Rayquaza set. Sold in multiples of six, with the best per-box price from 24 boxes — or buy the 12-box case.'],
    ['id'=>'abyss-eye-elite-trainer-box', 'sku'=>'FK-ETB-AE-01',
     'name'=>'Abyss Eye Elite Trainer Box', 'set'=>'Abyss Eye', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,42.00],[6,35.50],[18,33.60],[36,32.00]],
     'desc'=>'Elite Trainer Box for the Abyss Eye expansion. Sealed Japanese release with sleeves, dice, counters and promo card.'],
    ['id'=>'30th-celebration-greninja-ex-box', 'sku'=>'FK-PRM-GRE-01',
     'name'=>'30th Celebration Greninja ex Box', 'set'=>'30th Celebration', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.6, 'hidden'=>false,
     'ladder'=>[[1,21.56],[6,19.40],[18,16.80],[36,14.60]],
     'desc'=>'Special collection box built around the promo Greninja ex, with additional booster packs. Strong single-unit retail margin at case pricing.'],
    ['id'=>'heat-wave-arena-sv9a-booster-box', 'sku'=>'FK-BB-SV9A-01',
     'name'=>'Heat Wave Arena (SV9a) Booster Box', 'set'=>'Heat Wave Arena', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,207.11],[6,197.70],[18,186.00],[36,177.00]],
     'desc'=>'Sealed SV9a Heat Wave Arena booster box, Japanese domestic release. Consistent reorder line for shops running draft and league events.'],
    ['id'=>'glory-of-team-rocket-sv10-booster-box', 'sku'=>'FK-BB-SV10-01',
     'name'=>'Glory of Team Rocket (SV10) Booster Box', 'set'=>'Glory of Team Rocket', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,261.40],[6,249.50],[18,235.00],[36,223.40]],
     'desc'=>'Sealed SV10 Glory of Team Rocket booster box. One of the strongest secondary-market sets of the year; allocation moves quickly.'],
    ['id'=>'mega-start-deck-100-battle-collection', 'sku'=>'FK-PRM-MSD100-01',
     'name'=>'MEGA Start Deck 100 Battle Collection', 'set'=>'', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>12, 'step'=>12, 'status'=>'in', 'release'=>'', 'weight'=>1.2, 'hidden'=>false,
     'ladder'=>[[1,37.11],[12,35.40],[72,31.70]],
     'desc'=>'Sealed MEGA Start Deck 100 Battle Collection: ready-to-play decks aimed at new players and league nights. Sold by the case of 12, with the lowest price from 72.'],
    ['id'=>'starter-set-ex-zorua-and-zoroark-ex', 'sku'=>'FK-PRM-SSZOR-01',
     'name'=>'Starter Set ex — Zorua & Zoroark ex', 'set'=>'', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>12, 'step'=>12, 'status'=>'in', 'release'=>'', 'weight'=>0.35, 'hidden'=>false,
     'ladder'=>[[1,37.11],[12,35.40],[72,31.70]],
     'desc'=>'Starter Set ex with a ready-to-play Zorua and Zoroark ex deck. A low-price entry product that sells well next to booster boxes. Sold by the case of 12.'],
    ['id'=>'premium-trainer-box-mega', 'sku'=>'FK-PRM-PTBM-01',
     'name'=>'Premium Trainer Box MEGA', 'set'=>'', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>4, 'step'=>4, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,91.40],[4,87.20],[24,78.10]],
     'desc'=>'Sealed Premium Trainer Box MEGA from the Mega Evolution era. Sold in fours, with the lowest per-unit price from 24.'],
    ['id'=>'151-booster-box', 'sku'=>'FK-BB-SV2A-01',
     'name'=>'151 Booster Box', 'set'=>'151', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,445.71],[6,425.40],[36,380.90]],
     'desc'=>'Sealed Japanese 151 (SV2a) booster box — the special expansion built around the original 151 Pokémon, and one of the most collected Japanese sets of recent years. Sold in multiples of six.'],
    ['id'=>'151-charizard-ex-special-illustration-rare', 'sku'=>'FK-SGL-CHAR-151',
     'name'=>'151 Charizard ex — Special Illustration Rare', 'set'=>'151', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,328.80],[6,297.70]],
     'desc'=>'Japanese Charizard ex Special Illustration Rare from 151 (SV2a). Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'storm-emeralda-booster-box-case-12-ct', 'sku'=>'FK-BB-M6-C12',
     'name'=>'Storm Emeralda Booster Box Case (12-ct)', 'set'=>'Storm Emeralda', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>5.6, 'hidden'=>false,
     'ladder'=>[[1,1635.00],[6,1463.70]],
     'desc'=>'A factory-sealed case of 12 Storm Emeralda (M6) Japanese booster boxes, priced per case. The simplest way to stock Storm Emeralda in volume, with a lower case price from six cases.'],
    ['id'=>'aura-seeker-booster-box', 'sku'=>'FK-BB-MLZ-01',
     'name'=>'Aura Seeker (Hadou Seeker) Booster Box', 'set'=>'Aura Seeker (Hadou Seeker)', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'preorder', 'release'=>'November 2026', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,121.43],[6,115.90],[18,109.50],[36,103.80]],
     'desc'=>'Preorder allocation for the Japanese Aura Seeker (Hadou Seeker) booster box. Preorders are invoiced at allocation, not at request, at the quantity-break prices shown.'],
    ['id'=>'starter-set-ex-eevee-ex', 'sku'=>'FK-PRM-SSEEV-01',
     'name'=>'Starter Set ex — Eevee ex', 'set'=>'', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>10, 'step'=>10, 'status'=>'in', 'release'=>'', 'weight'=>0.35, 'hidden'=>false,
     'ladder'=>[[1,75.00],[10,59.00],[60,51.00]],
     'desc'=>'Starter Set ex with a ready-to-play Eevee ex deck — an easy first purchase for new players. Sold by the case of 10, with the lowest price from 60.'],
    ['id'=>'pokemon-tcg-card-storage-box-booster-box-display', 'sku'=>'FK-ACC-STOR-01',
     'name'=>'Pokémon TCG Card Storage Box — Booster Box Display', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.25, 'hidden'=>false,
     'ladder'=>[[1,8.82],[6,7.90],[36,6.00]],
     'desc'=>'Card storage box styled as a booster box display, for sleeved or loose cards on shelves and counters. Sold in sixes.'],
    ['id'=>'pokemon-tcg-9-pocket-binder-mega-evolution-series', 'sku'=>'FK-ACC-BIND-ME',
     'name'=>'Pokémon TCG 9-Pocket Binder — Mega Evolution Series', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.45, 'hidden'=>false,
     'ladder'=>[[1,31.36],[6,27.90],[36,20.30]],
     'desc'=>'9-pocket binder with Mega Evolution series artwork, for collections and trade binders. Sold in sixes, with the lowest price from 36.'],
    ['id'=>'celebi-and-furret-deck-sleeves', 'sku'=>'FK-ACC-SLV-CELF',
     'name'=>'Celebi & Furret Deck Sleeves', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>24, 'step'=>24, 'status'=>'in', 'release'=>'', 'weight'=>0.06, 'hidden'=>false,
     'ladder'=>[[1,12.73],[24,11.50],[144,8.60]],
     'desc'=>'Deck sleeves with Celebi and Furret artwork. Sold in 24s, with the lowest price from 144 packs.'],
    ['id'=>'pikachu-ditto-ver-deck-sleeves', 'sku'=>'FK-ACC-SLV-PIKD',
     'name'=>'Pikachu (Ditto Ver.) Deck Sleeves', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>24, 'step'=>24, 'status'=>'in', 'release'=>'', 'weight'=>0.06, 'hidden'=>false,
     'ladder'=>[[1,12.73],[24,11.50],[144,8.60]],
     'desc'=>'Deck sleeves featuring Pikachu in its Ditto version artwork. Sold in 24s, with the lowest price from 144 packs.'],
    ['id'=>'storm-emeralda-mega-rayquaza-deck-sleeves', 'sku'=>'FK-ACC-SLV-MRAY',
     'name'=>'Storm Emeralda Mega Rayquaza Deck Sleeves', 'set'=>'Storm Emeralda', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>24, 'step'=>24, 'status'=>'in', 'release'=>'', 'weight'=>0.06, 'hidden'=>false,
     'ladder'=>[[1,12.73],[24,11.50],[144,8.60]],
     'desc'=>'Mega Rayquaza deck sleeves from the Storm Emeralda release — a natural add-on to Storm Emeralda boxes. Sold in 24s.'],
    ['id'=>'ultra-pro-pikachu-alcove-tower-deck-box', 'sku'=>'FK-ACC-UP-ALCT',
     'name'=>'Ultra PRO Pikachu Alcove Tower Deck Box', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>12, 'step'=>12, 'status'=>'in', 'release'=>'', 'weight'=>0.2, 'hidden'=>false,
     'ladder'=>[[1,20.59],[12,18.50],[72,13.90]],
     'desc'=>'Ultra PRO Alcove Tower deck box with Pikachu artwork. Sold in 12s, with the lowest price from 72.'],
    ['id'=>'ultra-pro-pikachu-deck-protector-sleeves-65-ct', 'sku'=>'FK-ACC-UP-SLV65',
     'name'=>'Ultra PRO Pikachu Deck Protector Sleeves (65 ct)', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>24, 'step'=>24, 'status'=>'in', 'release'=>'', 'weight'=>0.06, 'hidden'=>false,
     'ladder'=>[[1,10.78],[24,9.10],[144,5.40]],
     'desc'=>'Ultra PRO Deck Protector sleeves with Pikachu artwork, 65 sleeves per pack. Sold in 24s, with the lowest price from 144 packs.'],
    ['id'=>'pokemon-playmat-assorted-designs', 'sku'=>'FK-ACC-MAT-AST',
     'name'=>'Pokémon Playmat — Assorted Designs', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>10, 'step'=>5, 'status'=>'in', 'release'=>'', 'weight'=>0.45, 'hidden'=>false,
     'ladder'=>[[1,28.00],[10,22.00],[50,19.00]],
     'desc'=>'Pokémon playmats in assorted designs; the mix of designs varies by shipment. Minimum 10, then in fives, with the lowest price from 50.'],
    ['id'=>'pokemon-deck-box-assorted', 'sku'=>'FK-ACC-DBX-AST',
     'name'=>'Pokémon Deck Box — Assorted', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>20, 'step'=>10, 'status'=>'in', 'release'=>'', 'weight'=>0.1, 'hidden'=>false,
     'ladder'=>[[1,12.00],[20,9.40],[100,8.00]],
     'desc'=>'Pokémon deck boxes in assorted designs; the mix varies by shipment. Minimum 20, then in tens, with the lowest price from 100.'],
    ['id'=>'pokemon-card-sleeves-64-ct-assorted-designs', 'sku'=>'FK-ACC-SLV64-AST',
     'name'=>'Pokémon Card Sleeves (64 ct) — Assorted Designs', 'set'=>'', 'cat'=>'accessories', 'cond'=>'Sealed',
     'moq'=>20, 'step'=>10, 'status'=>'in', 'release'=>'', 'weight'=>0.06, 'hidden'=>false,
     'ladder'=>[[1,8.00],[20,6.20],[100,5.20]],
     'desc'=>'Pokémon card sleeves, 64 per pack, in assorted designs; the mix varies by shipment. Minimum 20, then in tens.'],
    ['id'=>'mega-rayquaza-ex-sar-245-191-near-mint', 'sku'=>'FK-SGL-MRAY-SAR245',
     'name'=>'Mega Rayquaza ex SAR #245/191 — Near Mint', 'set'=>'Storm Emeralda', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>3, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,120.00],[3,102.00],[25,90.00]],
     'desc'=>'Japanese Mega Rayquaza ex Special Illustration Rare, card 245/191 from Storm Emeralda. Near Mint, sleeved and toploaded on dispatch. Minimum three copies, with the lowest price from 25.'],
    ['id'=>'pikachu-ex-sar-240-191-psa-10-gem-mint', 'sku'=>'FK-SGL-PIKA-PSA10',
     'name'=>'Pikachu ex SAR #240/191 — PSA 10 Gem Mint', 'set'=>'', 'cat'=>'singles', 'cond'=>'Graded',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.15, 'hidden'=>false,
     'ladder'=>[[1,495.00],[3,470.00]],
     'desc'=>'Pikachu ex Special Illustration Rare #240/191, graded PSA 10 Gem Mint and supplied in its PSA slab.'],
    ['id'=>'mega-floette-ex-japanese', 'sku'=>'FK-SGL-MFLO',
     'name'=>'Mega Floette ex (Japanese)', 'set'=>'Ninja Spinner', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,56.40],[6,51.00]],
     'desc'=>'Japanese Mega Floette ex from Ninja Spinner. Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'mega-excadrill-ex-japanese', 'sku'=>'FK-SGL-MEXC',
     'name'=>'Mega Excadrill ex (Japanese)', 'set'=>'Abyss Eye', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,65.80],[6,59.50]],
     'desc'=>'Japanese Mega Excadrill ex from Abyss Eye. Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'mega-greninja-ex-japanese', 'sku'=>'FK-SGL-MGRE',
     'name'=>'Mega Greninja ex (Japanese)', 'set'=>'Ninja Spinner', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,84.60],[6,76.60]],
     'desc'=>'Japanese Mega Greninja ex from Ninja Spinner. Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'mega-darkrai-ex-japanese', 'sku'=>'FK-SGL-MDRK',
     'name'=>'Mega Darkrai ex (Japanese)', 'set'=>'Abyss Eye', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,182.30],[6,165.00]],
     'desc'=>'Japanese Mega Darkrai ex from Abyss Eye. Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'pikachu-ex-special-illustration-rare-277-217', 'sku'=>'FK-SGL-PIKA-SAR277',
     'name'=>'Pikachu ex — Special Illustration Rare #277/217', 'set'=>'', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,362.70],[6,328.30]],
     'desc'=>'Pikachu ex Special Illustration Rare, card 277/217. Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'mega-charizard-y-ex-hyper-rare', 'sku'=>'FK-SGL-MCHY-HR',
     'name'=>'Mega Charizard Y ex — Hyper Rare', 'set'=>'', 'cat'=>'singles', 'cond'=>'Near Mint',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>0.05, 'hidden'=>false,
     'ladder'=>[[1,410.60],[6,371.70]],
     'desc'=>'Mega Charizard Y ex Hyper Rare. Near Mint, sleeved and toploaded on dispatch.'],
    ['id'=>'30th-celebration-premium-deck-set-espeon-and-umbreon', 'sku'=>'FK-PRM-30C-ESUM',
     'name'=>'30th Celebration Premium Deck Set — Espeon & Umbreon', 'set'=>'30th Celebration', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>1.2, 'hidden'=>false,
     'ladder'=>[[1,432.80],[6,371.70]],
     'desc'=>'Premium Deck Set from the 30th Celebration series, featuring Espeon and Umbreon. A collector-focused anniversary piece, sold individually with a lower price from six.'],
    ['id'=>'30th-celebration-sylveon-ex-box', 'sku'=>'FK-PRM-SYL-01',
     'name'=>'30th Celebration Sylveon ex Box', 'set'=>'30th Celebration', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.6, 'hidden'=>false,
     'ladder'=>[[1,21.56],[6,19.40],[36,14.60]],
     'desc'=>'Special collection box from the 30th Celebration series built around Sylveon ex, the companion to the Greninja ex box. Sold in sixes, with the lowest price from 36.'],
    ['id'=>'30th-celebration-tech-sticker-collection', 'sku'=>'FK-PRM-30C-STK',
     'name'=>'30th Celebration Tech Sticker Collection', 'set'=>'30th Celebration', 'cat'=>'premium', 'cond'=>'Sealed',
     'moq'=>12, 'step'=>12, 'status'=>'in', 'release'=>'', 'weight'=>0.25, 'hidden'=>false,
     'ladder'=>[[1,14.70],[12,13.20],[72,10.00]],
     'desc'=>'30th Celebration Tech Sticker Collection — a low-price add-on for counters and online baskets. Sold in 12s, with the lowest price from 72.'],
    ['id'=>'pitch-black-elite-trainer-box', 'sku'=>'FK-ETB-PB-01',
     'name'=>'Pitch Black Elite Trainer Box', 'set'=>'Abyss Eye', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>4, 'step'=>4, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,44.09],[4,39.60],[24,29.90]],
     'desc'=>'Pitch Black Elite Trainer Box, factory sealed, from our Abyss Eye range. Sold in fours, with the lowest per-unit price from 24.'],
    ['id'=>'chaos-rising-elite-trainer-box', 'sku'=>'FK-ETB-CR-01',
     'name'=>'Chaos Rising Elite Trainer Box', 'set'=>'Ninja Spinner', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>4, 'step'=>4, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,44.09],[4,39.60],[24,29.90]],
     'desc'=>'Chaos Rising Elite Trainer Box, factory sealed, from our Ninja Spinner range. Sold in fours, with the lowest per-unit price from 24.'],
    ['id'=>'perfect-order-elite-trainer-box', 'sku'=>'FK-ETB-PO-01',
     'name'=>'Perfect Order Elite Trainer Box', 'set'=>'Nihil Zero', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>4, 'step'=>4, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,44.09],[4,39.60],[24,29.90]],
     'desc'=>'Perfect Order Elite Trainer Box, factory sealed, from our Nihil Zero range. Sold in fours, with the lowest per-unit price from 24.'],
    ['id'=>'mega-evolution-ascended-heroes-elite-trainer-box', 'sku'=>'FK-ETB-AH-01',
     'name'=>'Mega Evolution: Ascended Heroes Elite Trainer Box', 'set'=>'Mega Dream ex', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>4, 'step'=>4, 'status'=>'in', 'release'=>'', 'weight'=>0.9, 'hidden'=>false,
     'ladder'=>[[1,44.09],[4,39.60],[24,29.90]],
     'desc'=>'Mega Evolution: Ascended Heroes Elite Trainer Box, factory sealed, from our Mega Dream ex range. Sold in fours, with the lowest per-unit price from 24.'],
    ['id'=>'30th-celebration-elite-trainer-box-case-10-ct', 'sku'=>'FK-ETB-30C-C10',
     'name'=>'30th Celebration Elite Trainer Box Case (10-ct)', 'set'=>'30th Celebration', 'cat'=>'etb', 'cond'=>'Sealed',
     'moq'=>1, 'step'=>1, 'status'=>'in', 'release'=>'', 'weight'=>10, 'hidden'=>false,
     'ladder'=>[[1,440.50],[6,331.70]],
     'desc'=>'A sealed case of 10 30th Celebration Elite Trainer Boxes, priced per case, with a much lower case price from six cases.'],
    ['id'=>'mega-dream-ex-m2a-booster-box', 'sku'=>'FK-BB-M2A-01',
     'name'=>'Mega Dream ex (M2A) Booster Box', 'set'=>'Mega Dream ex', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,175.00],[6,149.00],[24,136.00]],
     'desc'=>'Sealed Japanese Mega Dream ex (M2a) booster box — the set behind the Mega Gengar ex Special Illustration Rare. Sold in multiples of six, with the best per-box price from 24.'],
    ['id'=>'inferno-x-booster-box', 'sku'=>'FK-BB-INFX-01',
     'name'=>'Inferno X Booster Box', 'set'=>'Inferno X', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,217.10],[6,207.20],[36,185.50]],
     'desc'=>'Sealed Japanese Inferno X booster box from the Mega Evolution series. Sold in multiples of six, with the best per-box price from 36.'],
    ['id'=>'mega-symphonia-booster-box', 'sku'=>'FK-BB-M1S-01',
     'name'=>'Mega Symphonia Booster Box', 'set'=>'Mega Symphonia', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,109.97],[6,105.00],[36,94.00]],
     'desc'=>'Sealed Japanese Mega Symphonia booster box, one of the twin sets that opened the Mega Evolution era alongside Mega Brave. Sold in multiples of six.'],
    ['id'=>'mega-brave-booster-box', 'sku'=>'FK-BB-M1L-01',
     'name'=>'Mega Brave Booster Box', 'set'=>'Mega Brave', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,119.97],[6,114.50],[36,102.50]],
     'desc'=>'Sealed Japanese Mega Brave booster box, one of the twin sets that opened the Mega Evolution era alongside Mega Symphonia. Sold in multiples of six.'],
    ['id'=>'abyss-eye-m5-booster-box', 'sku'=>'FK-BB-M5-01',
     'name'=>'Abyss Eye (M5) Booster Box', 'set'=>'Abyss Eye', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,198.00],[6,168.00],[24,152.00]],
     'desc'=>'Sealed Japanese Abyss Eye (M5) booster box — the set behind the Mega Darkrai ex and Mega Excadrill ex singles. Sold in multiples of six, with the best per-box price from 24.'],
    ['id'=>'ninja-spinner-m4-booster-box', 'sku'=>'FK-BB-M4-01',
     'name'=>'Ninja Spinner (M4) Booster Box', 'set'=>'Ninja Spinner', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'low', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,165.00],[6,141.00],[24,129.00]],
     'desc'=>'Sealed Japanese Ninja Spinner (M4) booster box — the set behind Mega Greninja ex and Mega Floette ex. Limited stock left. Sold in multiples of six.'],
    ['id'=>'nihil-zero-booster-box', 'sku'=>'FK-BB-NZ-01',
     'name'=>'Nihil Zero Booster Box', 'set'=>'Nihil Zero', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,83.30],[6,82.60],[36,81.20]],
     'desc'=>'Sealed Japanese Nihil Zero booster box from the Mega Evolution series. Sold in multiples of six.'],
    ['id'=>'terastal-festival-booster-box', 'sku'=>'FK-BB-SV8A-01',
     'name'=>'Terastal Festival Booster Box', 'set'=>'Terastal Festival ex', 'cat'=>'boxes', 'cond'=>'Sealed',
     'moq'=>6, 'step'=>6, 'status'=>'in', 'release'=>'', 'weight'=>0.4, 'hidden'=>false,
     'ladder'=>[[1,88.20],[6,85.10],[36,78.40]],
     'desc'=>'Sealed Japanese Terastal Festival ex (SV8a) booster box, the special Scarlet & Violet set built around Terastal Pokémon and the Eevee evolutions. Sold in multiples of six.'],
  ],

  /* countries: '*' = everywhere, or a list of country codes */
  'payments' => [
    'crypto'   => ['label'=>'Cryptocurrency',   'note'=>'BTC, ETH or USDT (TRC-20 / ERC-20). Network fees are the sender\'s.', 'countries'=>'*', 'enabled'=>true],
    'cashapp'  => ['label'=>'Cash App',         'note'=>'US customers only.', 'countries'=>['US'], 'enabled'=>true],
    'applepay' => ['label'=>'Apple Pay',        'note'=>'US customers only.', 'countries'=>['US'], 'enabled'=>true],
    'ukbank'   => ['label'=>'UK bank transfer', 'note'=>'UK customers only. Faster Payments to a UK account in our business name.', 'countries'=>['GB'], 'enabled'=>true],
    'other'    => ['label'=>'Other / discuss with us', 'note'=>'Tell us what works and we will arrange it.', 'countries'=>'*', 'enabled'=>true],
  ],

  'countries' => ['US'=>'United States','GB'=>'United Kingdom','CA'=>'Canada','AU'=>'Australia','JP'=>'Japan','DE'=>'Germany','FR'=>'France','ES'=>'Spain','IT'=>'Italy','NL'=>'Netherlands','BE'=>'Belgium','SE'=>'Sweden','NO'=>'Norway','DK'=>'Denmark','FI'=>'Finland','IE'=>'Ireland','PL'=>'Poland','PT'=>'Portugal','CH'=>'Switzerland','AT'=>'Austria','CZ'=>'Czechia','GR'=>'Greece','SG'=>'Singapore','MY'=>'Malaysia','TH'=>'Thailand','PH'=>'Philippines','ID'=>'Indonesia','VN'=>'Vietnam','KR'=>'South Korea','TW'=>'Taiwan','HK'=>'Hong Kong','NZ'=>'New Zealand','MX'=>'Mexico','BR'=>'Brazil','AR'=>'Argentina','CL'=>'Chile','ZA'=>'South Africa','AE'=>'United Arab Emirates','SA'=>'Saudi Arabia','IL'=>'Israel','TR'=>'Turkey','IN'=>'India','NG'=>'Nigeria','KE'=>'Kenya','EG'=>'Egypt','CM'=>'Cameroon','GH'=>'Ghana'],

  /* shipping (USD) = zone base per order + per_kg × total order weight.
     PLACEHOLDER RATES — set real ones in Admin → Shipping before going live. */
  'shipping' => [
    'zones' => [
      ['name'=>'Japan',            'countries'=>['JP'], 'base'=>8,  'per_kg'=>2],
      ['name'=>'United States',    'countries'=>['US'], 'base'=>18, 'per_kg'=>14],
      ['name'=>'Canada',           'countries'=>['CA'], 'base'=>18, 'per_kg'=>14],
      ['name'=>'United Kingdom',   'countries'=>['GB'], 'base'=>16, 'per_kg'=>12],
      ['name'=>'Europe',           'countries'=>['DE','FR','ES','IT','NL','BE','SE','NO','DK','FI','IE','PL','PT','CH','AT','CZ','GR'], 'base'=>16, 'per_kg'=>12],
      ['name'=>'Asia-Pacific',     'countries'=>['SG','MY','TH','PH','ID','VN','KR','TW','HK','AU','NZ'], 'base'=>10, 'per_kg'=>8],
    ],
    'rest' => ['base'=>22, 'per_kg'=>16],
  ],

  /* placeholders: {reply_hours} {hold_hours} {countries} {min_order} */
  'faqs' => [
    ['Do I need an account to see wholesale pricing?', 'No. Every product shows its full quantity-break ladder publicly, so you can price a complete order before contacting anyone. There is no application form and no approval wait.'],
    ['What is the minimum order?', 'Every order must total at least {min_order} including shipping. Sealed product starts at six units and sells in multiples of six. Graded and raw singles start at one, with breaks from three and six.'],
    ['How do I pay?', 'Select a method at checkout — cryptocurrency, Cash App or Apple Pay for US customers, UK bank transfer for UK customers, or the "other" option anywhere else. We send the details for your chosen method to your email and phone within {reply_hours} hours, with your invoice.'],
    ['When is my stock allocated?', 'Placing an order reserves your stock for {hold_hours} hours. Once payment clears, the allocation is confirmed and we dispatch within {hold_hours} hours. If payment does not clear inside the window, high-demand stock returns to general availability.'],
    ['Which countries do you ship to?', '{countries} countries from Japan by EMS, DHL and FedEx with tracking on every consignment. Shipping is calculated at checkout from your destination and order weight. Import duty, VAT or GST and clearance fees are excluded from our prices and collected by your carrier on delivery.'],
    ['Can I preorder an upcoming set?', 'Yes. Preorder lines commit an allocation ahead of release at the same published ladder, and are invoiced at allocation rather than at request.'],
    ['Is the product authentic?', 'Yes. Everything is sourced through Japanese distribution and ships sealed in its original factory packaging. We do not deal in resealed, reprinted or counterfeit product.'],
    ['What if something arrives damaged or short?', 'Report transit damage, a short shipment or a wrong item within seven days of delivery and we replace, credit or refund the affected lines and their shipping.'],
  ],
];
